name: salim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # youtube_player_flutter: ^7.0.0+6
  # google_maps_flutter: ^0.5.30
  chewie: ^0.9.10
  video_player: ^0.10.11+2
  # image_picker: ^0.6.7+4
  cupertino_icons: ^0.1.3
  flutter_pdfview: ^1.0.3+3
  path_provider: ^1.6.11
  # pdf: ^1.10.1
  # printing: ^3.6.0
  url_launcher: ^5.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/indicator_BC.png
    - assets/result_BC.png
    - assets/result_BC_r.png
    - assets/salim_avatar.png
    - assets/salimAvatar.png
    - assets/partners.png
    - assets/attention.png
    - assets/salim_logo.png
    - assets/last_logo1.png
    - assets/alarm.png
    - assets/icons/
    - assets/info/
    - assets/indicators/
    - assets/result_ind/
    - assets/result_img/
    - assets/sd_logo.png
    - assets/videos/out.mp4
    - assets/videos/use_app.mp4
    - assets/pdfs/
    - assets/web1.png
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.ttf
        - asset: assets/fonts/REGULAR.ttf
